bin

diff --git a/bin/pass b/bin/pass
--- a/bin/pass
+++ b/bin/pass
@@ -17,12 +17,13 @@ if [ ! -f list ];then
 else
 	LIST="list"
 fi
-for i in `cat $LIST`
+for DIR in `cat $LIST`
 do
+   NAME=`basename $DIR`
    BUILD="yes"
-   PKGMK="pkgmk"
-   if [ -f ${LOG}/$i.log ]; then
-      if ( grep "^=======>" ${LOG}/$i.log| tail -1 |grep "succeeded"  > /dev/null);then
+   PKGMK="pkgmk.passes"
+   if [ -f ${LOG}/$NAME.log ]; then
+      if ( grep "^=======>" ${LOG}/$NAME.log|grep "succeeded"  > /dev/null);then
          BUILD="no"
       else
          BUILD="yes"
@@ -30,21 +31,84 @@ do
 
    fi
    if [ "$BUILD" == "yes" ]; then
-      if [ "$PASS" == "CHROOT" ]; then
-           cd ${i}
-      else
-         cd ${i}#*
-      fi
-      NAME=`echo $i|cut -d "#" -f1`
-      if [ "$NAME" != "kernel" ];then
-      	$PKGMK -cf ../../config/pkgmk.conf -i -kw 2>&1|tee ${LOG}/$i.log || exit 1
-      else
-        $PKGMK -cf ../../config/pkgmk.conf -i -kw
-      fi
-      if ( grep "^=======>" ${LOG}/$i.log| tail -1 |grep "ERROR"  > /dev/null);then
+      cd $DIR
+      case $PASS in
+       chroot)
+        PKGMK="pkgmk.passes"
+        $PKGMK -cf ../../config/pkgmk.conf -kw 2>&1|tee ${LOG}/$NAME.log || exit 1;;
+       base)
+        PKGMK="pkgmk"
+        case $NAME in
+	  gcc)
+		$PKGMK -cf ../../config/pkgmk.conf -kw 2>&1|tee ${LOG}/$NAME.log || exit 1
+		rm -fv /usr/lib{,64}/libgcc_s.so{,.1}
+		rm -fv /usr/lib{,64}/libstdc++.so{,.6}
+		rm -fv /usr/lib{,64}/libstdc++.la
+		$PKGMK -d -cf ../../config/pkgmk.conf -i || exit 1
+		for i in *cards.tar*
+		do
+		 echo "=======> Installing '$i' succeeded." >> ${LOG}/$NAME.log
+		done
+		;;
+
+	   bash)
+		$PKGMK -cf ../../config/pkgmk.conf -kw 2>&1|tee ${LOG}/$NAME.log || exit 1
+		rm /bin/bash
+		rm /bin/sh
+		echo "need to install bash manually"
+		echo "=======> Installing '$NAME' succeeded." >> ${LOG}/$NAME.log
+		exit 1
+		$PKGMK -d -cf ../../config/pkgmk.conf -i
+		;;
+
+	  coreutils)
+		$PKGMK -cf ../../config/pkgmk.conf -kw 2>&1|tee ${LOG}/$NAME.log || exit 1
+		rm -f /usr/bin/env
+		for i in cat echo pwd stty
+		do
+			rm -f /bin/$i
+		done
+		$PKGMK -d -cf ../../config/pkgmk.conf -i || exit 1
+		for i in *cards.tar*
+		do
+		  echo "=======> Installing '$i' succeeded." >> ${LOG}/$NAME.log
+		done
+		;;
+
+	  perl)
+		$PKGMK -cf ../../config/pkgmk.conf -kw 2>&1|tee ${LOG}/$NAME.log || exit 1
+		rm -f /usr/bin/perl
+		$PKGMK -d -cf ../../config/pkgmk.conf -i || exit 1
+		for i in *cards.tar*
+		do
+			echo "=======> Installing '$i' succeeded." >> ${LOG}/$NAME.log
+		done
+		;;
+	  cards)
+		$PKGMK -cf ../../config/pkgmk.conf -kw 2>&1|tee ${LOG}/$NAME.log || exit 1
+		rm -f /etc/pkgadd.conf
+		$PKGMK -d -cf ../../config/pkgmk.conf -i || exit 1
+		for i in *cards.tar*
+		do
+			echo "=======> Installing '$i' succeeded." >> ${LOG}/$NAME.log
+		done
+		;;
+	  kernel)
+		$PKGMK -d -cf ../../config/pkgmk.conf -i -kw || exit 1
+		echo "=======> Installing '$NAME' succeeded." >> ${LOG}/$NAME.log
+		;;
+
+	  *)
+		$PKGMK -cf ../../config/pkgmk.conf -i -kw 2>&1|tee ${LOG}/$NAME.log || exit 1
+		;;
+        esac;;
+       *)
+        PKGMK="pkgmk -d -i"
+        $PKGMK  2>&1|tee ${LOG}/$NAME.log || exit 1;;
+      esac
+      if ( grep "^=======>" ${LOG}/$NAME.log| tail -1 |grep "ERROR"  > /dev/null);then
          exit 1
       fi
-      cd ..
+      cd -
    fi
 done
-
